export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_PARTIAL = "SET_LOADING_PARTIAL";

// ERRORS AND MESSAGES
export const SET_ERROR_MSGS = "SET_ERROR_MSGS";
export const DELETE_INDIVIDUAL_ERROR_MSG = "DELETE_INDIVIDUAL_ERROR_MSG";
export const DELETE_ALL_ERROR_MSG = "DELETE_ALL_ERROR_MSG";
export const SET_MESSAGES = "SET_MESSAGES";
export const DELETE_INDIVIDUAL_MSG = "DELETE_INDIVIDUAL_MSG";
export const DELETE_ALL_MSG = "DELETE_ALL_MSG";

// USERS
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

// MAIN
export const LOAD_TASKS = "LOAD_TASKS";
export const LOAD_PROCESSES = "LOAD_PROCESSES";
export const LOAD_NOTES = "LOAD_NOTES";
export const LOAD_COLLECTIONS = "LOAD_COLLECTIONS";
export const CHANGE_MODE = "CHANGE_MODE";

// TASKS
export const NEW_TASK_ADDED = "NEW_TASK_ADDED";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_TASk = "UPDATE_TASk";
export const FINISH_TASK = "FINISH_TASK";
export const UNFINISH_TASK = "UNFINISH_TASK";
// SUBTASKS
export const NEW_SUBTASK_ADDED = "NEW_SUBTASK_ADDED";
export const ADD_SUBTASK = "ADD_SUBTASK";
export const DELETE_SUBTASK = "DELETE_SUBTASK";

// NOTES
export const UPDATE_NOTE = "UPDATE_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const ADD_NOTE = "ADD_NOTE";

// COLLECTIONS
export const ADD_NEW_COLLECTION = "ADD_NEW_COLLECTION";
export const ADD_TO_COLLECTION = "ADD_TO_COLLECTION";
export const REMOVE_FROM_COLLECTION = "REMOVE_FROM_COLLECTION";
